# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings - Accessible via {{ site.myvariable }}.
title: "Laurent Renard Triché"
description: "Laurent Renard Triché personal page and blog"
url: "http://lrenardtriche.github.io/cv-ana"

# Build settings
markdown: kramdown
timezone: Europe/Paris

plugins:
  - jemoji
  - jekyll-feed
  - jekyll-redirect-from

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - cv_latex
